# Generated by Django 5.0.4 on 2026-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=128)),
                ('sop_instance_uid', models.CharField(max_length=128)),
                ('frame_number', models.IntegerField(default=0)),
                ('annotation_type', models.CharField(choices=[('length', 'Length'), ('angle', 'Angle'), ('roi', 'ROI'), ('arrow', 'Arrow'), ('text', 'Text'), ('ellipse', 'Ellipse'), ('rectangle', 'Rectangle')], max_length=20)),
                ('data', models.JSONField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
