# Generated by Django 5.0.4 on 2026-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthanc_id', models.CharField(max_length=64, unique=True)),
                ('study_instance_uid', models.CharField(max_length=128, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=64)),
                ('patient_birth_date', models.CharField(blank=True, max_length=16)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=255)),
                ('modalities', models.JSONField(default=list)),
                ('series_count', models.IntegerField(default=0)),
                ('instance_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
                'ordering': ['-study_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
